export {
  HomeIcon,
  GitHubIcon,
  SunIcon,
  MoonIcon,
  ComputerDesktopIcon,
  UserIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightStartOnRectangleIcon,
  BarsIcon,
  DocumentIcon,
  XMarkIcon,
  //
  DotsHorizontalIcon,
  ChevronSortIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  AngleLeftIcon,
  AngleRightIcon,
} from './icon.component';
