export type TIconKind =
  | 'LoginIcon'
  | 'SearchIcon'
  | 'MenuIcon'
  | 'NotificationsIcon'
  | 'PersonIcon'
  | 'LogoutIcon'
  | 'TuneIcon'
  | 'ReplayIcon'
  | 'CloseIcon'
  | 'LightModeIcon'
  | 'DarkModeIcon'
  | 'StarBorderIcon'
  | 'ExpandLessIcon'
  | 'ExpandMoreIcon'
  | 'WebIcon'
  | 'DashboardIcon'
